services:
  app:
    build: .
    container_name: music-watchdog
    volumes:
      - /path/on/host/to_process:/app/to_process
      - /path/on/host/processed_songs:/app/processed_songs
    # command: python main.py
    command: tail -f /dev/null

volumes:
  FILES_TO_PROCESS_DIR: {}
  PROCESS_FILES_DIR: {}