services:
  app:
    image: ghcr.io/subasically/music-watchdog:latest
    container_name: azuracast-music-watchdog
    volumes:
      - /path/on/host/to_process:/app/to_process
      - /path/on/host/processed_songs:/app/processed_songs
    command: python main.py

volumes:
  FILES_TO_PROCESS_DIR: {}
  PROCESS_FILES_DIR: {}