services:
  app:
    image: ghcr.io/subasically/music-watchdog:latest
    container_name: azuracast-music-watchdog
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}" # Set the user to match the host's UID and GID (find these using "id -u" and "id -g")
    environment:
      - TZ=America/Chicago
      - DEBUG=False
      - SLEEP_TIME_MINUTES=5
      # - SLACK_WEBHOOK_URL=""
      # - SFTP_USERNAME=""
      # - SFTP_HOST=""
      # - SFTP_PASSWORD=""
      # - SFTP_PORT=""
      # - SFTP_REMOTE_DIR=""
      # - SFTP_LOCAL_DIR=""
    volumes:
      - /path/on/host/to_process:/app/to_process
      - /path/on/host/processed_songs:/app/processed_songs
    command: python -u app/main.py

volumes:
  FILES_TO_PROCESS_DIR: {}
  PROCESS_FILES_DIR: {}