services:
  app:
    image: ghcr.io/subasically/music-watchdog:latest
    container_name: azuracast-music-watchdog
    volumes:
      - ./:/app
      - FILES_TO_PROCESS_DIR:/app/to_process
      - PROCESS_FILES_DIR:/app/processed_songs
    command: python shazam.py